### ISSUE TITLE
integration throws error in android

### ISSUE THREAD

**Issue by shaikhussian** [MattFoley/react-native-paypal#22]
hai when i am using react-native-papal, While integrating it in android it throws some errors like this in android. Below is the screen Shot for it 
![screen shot 2016-11-24 at 4 16 39 pm](https://cloud.githubusercontent.com/assets/11956308/20596239/8bf8c7ec-b263-11e6-8dc0-c57b4db21bb2.png)
please give me suggestions that how to resolve it

**Comment by franverona** [comment]
I'm actually facing the same issue. I was able to solve the first two error messages by setting both properties as `public` on my `MainApplicaiton.java` file like this:

```
public static final int PAY_PAL_REQUEST_ID = 9;
public PayPalPackage payPalPackage;
```

But I'm still having the last one:

```
error: constructor PayPalPackage in class PayPalPackage cannot be applied to given types;
      payPalPackage = new PayPalPackage(PAY_PAL_REQUEST_ID);
                      ^
  required: Context,int
  found: int
  reason: actual and formal argument lists differ in length
1 error
```

Any help or idea would be really appreciate it. Thanks!

Edit: I'm using **RN 0.35.0**, so I did all of what [this repository](https://github.com/sharafat/react-native-paypal) suggests to integrate this package with Android.

**Comment by franverona** [comment]
I solved it! I've just replaced Android folder's code with this version more updated: https://github.com/sharafat/react-native-paypal/tree/master/android/src/main/java/br/com/vizir/rn/paypal

That version supports RN > 0.29 and it should work.

**Comment by MattFoley** [comment]
Closing this in favor of https://github.com/MattFoley/react-native-paypal/issues/16 which has more information

**Comment by mahesh963** [comment]
I am working on a sample project, In that project i used MattFoley/react-native-paypal module for IOS platform and sharafat/react-native-paypal for android plaftorm. i merged the two Modules using platform specific code.for, IOS platform i used manually usage(i.e. the steps mentioned in the module) it's working fine and shows the paypal screen But, coming to Android i used the code


`let PayPal = require('react-native-paypal');
PayPal.paymentRequest({
  clientId: 'AbyfNDFV53djg6w4yYgiug_JaDfBSUiYI7o6NM9HE1CQ_qk9XxbUX0nwcPXXQHaNAWYtDfphQtWB3q4R',
  environment: PayPalAndroid.SANDBOX,
  price: '42.00',
  currency: 'USD',
  description: 'PayPal Test'
}).then((confirm, payment) => console.log('Paid'); /* At this point you should verify payment independently */)
.catch((error_code) => console.error('Failed to pay through PayPal'));`

paypal screen is not displaying and app is getting crashed while moving to paypal module screen  in Android platform.

**Comment by Bardoza** [comment]
@mahesh963 had the same issue, fixed it by replacing the whole android folder instead of just the java files
