### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by sangrit-siit** [MattFoley/react-native-paypal#23]
![simulator screen shot jan 17 2560 be 12 12 01 am](https://cloud.githubusercontent.com/assets/23272765/21992854/a405e7dc-dc4a-11e6-8950-33fad90cc176.png)

node -v
v7.4.0

react-native -v
react-native-cli: 1.0.0
react-native: 0.35.0

Please help !
I stuck with this, I have spend almost two days to solve this

**Comment by MattFoley** [comment]
Closing this in favor of https://github.com/MattFoley/react-native-paypal/issues/16 which has more information

**Comment by mmafawalla** [comment]
Were there any fixes to the above solution
