### ISSUE TITLE
Unable to install the repository

### ISSUE THREAD

**Issue by nidhi-tandon** [MattFoley/react-native-paypal#25]
I am trying to install using this command
npm install --save MattFoley/react-native-paypal
![screen shot 2017-05-09 at 6 21 05 pm](https://cloud.githubusercontent.com/assets/6941627/25851723/7f409ed6-34e4-11e7-9b27-2ffc7707bee6.png)

Hope someone can help me in this. Thanks

**Comment by Richi2293** [comment]
I used this "npm install --save react-native-paypal" and executed the command correctly.
(I only tested on Android and it works)

In iOS It doesn't works for me.

**Comment by alexaround25** [comment]
@MattFoley Have you manage to resolve the Permission denied (publickey). issue or the library is still valid for iOS? If yes, how can we install it? Thank you

**Comment by prasad456** [comment]
When I use npm install --save react-native-paypal, installing other package

**Comment by nidhi-tandon** [comment]
Closing this issue as I have lost context of it.
