### ISSUE TITLE
Freezes when there is network Error and Cant Even Access the Try again or Cancel Button

### ISSUE THREAD

**Issue by deresegetachew** [MattFoley/react-native-paypal#3]
@MattFoley So whats happening is When there is an SSL problem or a network problem and it cant access the paypal servers the try again or cancel dialogue buttons wont work; i have to wait for a minute or two for them to be responsive it basically freezes; 
![simulator screen shot jan 20 2016 10 41 21 am](https://cloud.githubusercontent.com/assets/2713659/12442661/d80ef95c-bf62-11e5-9cb2-f2483af97b73.png)

**Comment by deresegetachew** [comment]
@troublesome80 you might be interested in this too

**Comment by deresegetachew** [comment]
actually this is for all the message boxes

**Comment by MattFoley** [comment]
@derese This may have been because it was not being presented on the main thread. I updated it just now to do so.
