### ISSUE TITLE
Paypal Configuration needs extra parameter

### ISSUE THREAD

**Issue by deresegetachew** [MattFoley/react-native-paypal#4]
<img width="1162" alt="screen shot 2016-01-25 at 3 39 18 pm" src="https://cloud.githubusercontent.com/assets/2713659/12551209/d65d08d6-c379-11e5-8d5d-41ea3e4492db.png">
Under your app target -> build settings, look for Other Linker Flags and add $(inherited); other wise you will get error when building the project.

**Comment by deresegetachew** [comment]
@MattFoley I added this because this step is not included on their site or the link you provided and that step is important or else we get errors

**Comment by MattFoley** [comment]
It all depends on how you're linking in the PayPal library, there are 3 different ways to do that (Runtime Linking, Linker Flags, Xcode Build Phases UI). If you want to add some information on how to do that to the readme, that's okay with me, but I think most developers who are familiar with iOS will have a way of linking that they're used to, that won't be specific to this library.
