### ISSUE TITLE
getting Error: contains too many fractional digits.

### ISSUE THREAD

**Issue by deresegetachew** [MattFoley/react-native-paypal#5]
hey @MattFoley  need help;

when i am passing more than one digit like shown below i get an exception from Xcode.
MFLReactNativePayPal.preparePaymentOfAmount(5.8, "USD", "something");

PayPal SDK: PayPalPayment not processable: '5.80000019073486336' contains too many fractional digits. (For USD, can be no more than 2.)

**Comment by deresegetachew** [comment]
CGFloat is the one giving us problems; under preparePaymentOfAmount method

**Comment by deresegetachew** [comment]
converted the Method inside MFLReactNativePayPal.m  to use **double**  the changed method looks like the one below

`RCT_EXPORT_METHOD(preparePaymentOfAmount:(double)amount
                  ofCurrency:(NSString *)currencyCode
                  withDescription:(NSString *)description)
{
  self.payment = [[PayPalPayment alloc] init];
  [self.payment setAmount:[[NSDecimalNumber alloc] initWithDouble:amount]];
  [self.payment setCurrencyCode:currencyCode];
  [self.payment setShortDescription:description];
}
`

**Comment by MattFoley** [comment]
@erenn16 has made this fix, should be good to go for you now.
