### ISSUE TITLE
Adding invoice number and other optional Fields

### ISSUE THREAD

**Issue by deresegetachew** [MattFoley/react-native-paypal#6]
i needed to add invoice number which is an optional field  according 
https://github.com/paypal/PayPal-iOS-SDK/blob/master/docs/single_payment.md  
section 5 and its also found here in the PayPalPayment.h 
https://github.com/paypal/PayPal-iOS-SDK/blob/master/PayPalMobile/PayPalPayment.h

currently under this implementation optional fields are not supported but i was able to add invoice number by doing the following to our  MFLReactNativePayPal.m; i basically added a parameter of invoiceNumber of type string and set it to the payment object; here goes the code ;
on another note i also made the amount double because of error with digits with CGFloat Type

`RCT_EXPORT_METHOD(preparePaymentOfAmount:(double)amount
                  ofCurrency:(NSString *)currencyCode
                  withDescription:(NSString *)description
                  withInvoiceNumber:(NSString *) invoicenumber)
{
  self.payment = [[PayPalPayment alloc] init];
  [self.payment setAmount:[[NSDecimalNumber alloc] initWithDouble:amount]];
  [self.payment setCurrencyCode:currencyCode];
  [self.payment setShortDescription:description];
  [self.payment setInvoiceNumber:invoicenumber];

}`

**Comment by MattFoley** [comment]
I'd be happy to pull this in if you want to open a pull request!
