### ISSUE TITLE
3rd-Party Payment

### ISSUE THREAD

**Issue by ghost** [MattFoley/react-native-paypal#8]
Hello,

How can I use this `react-native-braintree` module to use 3rd-party Payments?

I am developing an E-Commerce Shop and I need the user payment directly to the shop who offers the product. As we have many different shops, the 'payee' difference depended on the product. How can I achieve this?

Thanks
Alexander Niebuhr

**Comment by MattFoley** [comment]
I would welcome a pull request to implement this feature, but don't have time to implement it myself.
